trigger:
  branches:
    include:
      - 'dev'
      - 'test'
      - 'main'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: StorageSecrets

  - name: storageAccountName
    value: 'saxdiprodweu001'
  
  - name: containerName
    value: 'xdi-metadata'
  
  - name: basePath
    value: 'meta/pipelines'
  
  - name: blobPath
    value: '$(Build.SourceBranchName)/'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install python dependencies'

  - script: |
      python tests/run.py
    displayName: 'Execute python tests'
    
  - script: |
      echo $(AZURE_STORAGE_KEY)
    displayName: 'Debug: Show Storage Key'

  - script: |
      echo "Uploading file to Azure Storage..."
      for file in $(find $(Build.SourcesDirectory)/$(basePath) -type f); do
        relativePath=${file#$(Build.SourcesDirectory)/}
        blobFilePath=$(echo "$relativePath" | sed "s|^|$(blobPath)|")

        az storage blob upload \
          --account-name $(storageAccountName) \
          --container-name $(containerName) \
          --file "$file" \
          --name "$blobFilePath" \
          --overwrite \
          --auth-mode key \
          --account-key $(AZURE_STORAGE_KEY)
      done
    displayName: 'Upload files to Azure Storage'
    env:
      AZURE_STORAGE_KEY: $(AZURE_STORAGE_KEY)
