name: customer-sales-backend-restapi-air

# RUN: docker compose -f restapi.air.docker-compose.yml up --build
# If the connection raises an error, maybe the database 'customersales' is not created yet.

services:
  restapi:
    container_name: customer-sales-backend-restapi-air
    build:
      context: ../../customer-sales-backend/restapi
      dockerfile: ../../docker/images/restapi.air.Dockerfile
    ports:
      - "8080:8080"
    environment:
      MODE: debug # debug, release
      DB_HOST: database
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: adminpw1!
      DB_NAME: customersales
    depends_on:
      - database
    networks:
      - app_network
    volumes:
      - ../../customer-sales-backend/restapi:/app
      - /app/bin
      - /app/air.log

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: customer-sales-backend-database-air
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=adminpw1! # username=sa
    ports:
      - "1433:1433"  # Default SQL Server port
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
