name: Build and Push restapi Image

on:
  push:
    branches:
      - noexecution
      # - dev
  pull_request:
    branches:
      - noexecution
      # - dev
      # - qa
      # - main

jobs:
  build-and-push-restapi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      run: echo "${{ secrets.AZURE_REPOSITORY_PASSWORD }}" | docker login eadbprojectweucr.azurecr.io -u ${{ secrets.AZURE_REPOSITORY_USERNAME }} --password-stdin
    
    - name: Determine Branch Name
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "branch_name=${{ github.base_ref }}" >> $GITHUB_ENV
        else
          echo "branch_name=${{ github.ref_name }}" >> $GITHUB_ENV
        fi

    - name: Build and tag Docker image
      run: |
        docker build --platform linux/amd64 -t eadbprojectweucr.azurecr.io/restapi:v1-${branch_name} -f docker/images/restapi.Dockerfile customer-sales-backend/restapi

    - name: Push Docker image to Azure Container Registry
      run: |
        docker push eadbprojectweucr.azurecr.io/restapi:v1-${branch_name}
